function cSampOffResCUDADoubles_v1i

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Compass\1 Scripts\zy NonMatlabSubRoutines\Set 1.5\CudaSubRoutines\zz Library';

mex('-R2017b',...                                         
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_GeneralD_v1c', ...
    '-lCUDA_FFTDoubles_v1c', ...
    '-lCUDA_FFTShiftD_v1e', ...
    '-lCUDA_PhaseAddOffResD_v2d', ...
    '-lCUDA_ConvGrid2SampSplitCD_v1e', ...    
    'SampOffResCUDADoubles_v1i.cpp');

 % -O = compile with opitmization        