function cSampOffResCUDADoubles2D_v1f

% CUDA Path
CUDApath = getenv('CUDA_LIB_PATH');      
if CUDApath(1) == '"' 
    CUDApath = CUDApath(2:end); 
end, 
if CUDApath(end) == '"'
    CUDApath = CUDApath(1:end-1);
end

% CUDA Lib Path
CUDAlib = 'D:\1 Scripts\zy NonMatlabSubRoutines\Set 1.4\CudaSubRoutines\zz Library';

mex('-largeArrayDims',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_2DGeneralD_v1a', ...
    '-lCUDA_FFTDoubles2D_v1a', ...
    '-lCUDA_FFTShiftD2D_v1c', ...
    '-lCUDA_PhaseAddOffResD_v2a', ...
    '-lCUDA_ConvGrid2SampSplitCD2D_v1c', ...    
    'SampOffResCUDADoubles2D_v1f.cpp');

 % -O = compile with opitmization        