function cSampOffResCUDADoubles_v1f

% CUDA Path
CUDApath = getenv('CUDA_LIB_PATH');      
if CUDApath(1) == '"' 
    CUDApath = CUDApath(2:end); 
end, 
if CUDApath(end) == '"'
    CUDApath = CUDApath(1:end-1);
end

% CUDA Lib Path
CUDAlib = 'D:\1 Scripts\zy NonMatlabSubRoutines\Set 1.4\CudaSubRoutines\zz Library';

mex('-largeArrayDims',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_GeneralD_v1a', ...
    '-lCUDA_FFTDoubles_v1a', ...
    '-lCUDA_FFTShiftD_v1c', ...
    '-lCUDA_PhaseAddOffResD_v2a', ...
    '-lCUDA_ConvGrid2SampSplitCD_v1c', ...    
    'SampOffResCUDADoubles_v1f.cpp');

 % -O = compile with opitmization        