function cSampOffResCUDADoubles_v1h

% CUDA Path
CUDApath = getenv('CUDA_LIB_PATH');      
%CUDApath = CUDApath(1:end-1);                  % remove last backslash

% CUDA Lib Path
CUDAlib = 'D:\1 Scripts\zy NonMatlabSubRoutines\Set 1.4\CudaSubRoutines\zz Library';

mex('-largeArrayDims',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_GeneralD_v1b', ...
    '-lCUDA_FFTDoubles_v1b', ...
    '-lCUDA_FFTShiftD_v1d', ...
    '-lCUDA_PhaseAddOffResD_v2c', ...
    '-lCUDA_ConvGrid2SampSplitCD_v1d', ...    
    'SampOffResCUDADoubles_v1h.cpp');

 % -O = compile with opitmization        